SELECT USER
FROM DUAL;
--==>> SCOTT

--○ 실습 테이블 생성
CREATE TABLE TBL_STUDENT
( SID   NUMBER
, NAME  VARCHAR2(30)
, TEL   VARCHAR2(40)
, CONSTRAINT STUDENT_SID_PK PRIMARY KEY(SID)
);
--==>> Table TBL_STUDENT이(가) 생성되었습니다.


--○ 실습 대상 시퀀스 구성
CREATE SEQUENCE STUDENTSEQ
NOCACHE;
--==>> Sequence STUDENTSEQ이(가) 생성되었습니다.

--○ 데이터 입력
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(STUDENTSEQ.NEXTVAL, '이새롬', '010-1111-1111');
--==>> 1 행 이(가) 삽입되었습니다.

--○ 리스트 조회
SELECT SID, NAME, TEL
FROM TBL_STUDENT
ORDER BY SID;
--==>> 1	이새롬	010-1111-1111

COMMIT;

--○ 인원 수 확인
SELECT COUNT(*) AS COUNT
FROM TBL_STUDENT;


--○ 데이터 추가 입력
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(STUDENTSEQ.NEXTVAL, '강아지', '010-2222-2222');


--○ 커밋
COMMIT;


--○ 데이터 삭제
DELETE
FROM TBL_STUDENT
WHERE SID=1;


--○ 테이블 생성
CREATE TABLE TBL_GRADE
( SID   NUMBER
, SUB1  NUMBER(3)
, SUB2  NUMBER(3)
, SUB3  NUMBER(3)
, CONSTRAINT GRADE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT GRADE_SID_FK FOREIGN KEY(SID)  REFERENCES TBL_STUDENT(SID)
);
--==>> Table TBL_GRADE이(가) 생성되었습니다.

ALTER TABLE TBL_STUDENT DROP CONSTRAINT TBL_STUDENT_PK;

--○ 데이터입력
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(1, 90, 80, 70);

--○ 리스트 조회
SELECT SID, SUB1, SUB2, SUB3
FROM TBL_GRADE
ORDER BY SID;
--==>> 1	90	80	70

COMMIT;

--○ 뷰 생성
CREATE OR REPLACE VIEW STUDENTVIEW
AS
SELECT SID, NAME, TEL, SUB
FROM TBL_STUDENT;










